MONGO_HOST: "mongodb-{{ env }}.naginenihariaws.store"
CATALOGUE_HOST: "catalogue-{{ env }}.naginenihariaws.store"
CART_HOST: "cart-{{ env }}.naginenihariaws.store"
USER_HOST: "user-{{ env }}.naginenihariaws.store"
MYSQL_HOST: "mysql-{{ env }}.naginenihariaws.store"
RABBITMQ_HOST: "rabbitmq-{{ env }}.naginenihariaws.store"
SHIPPING_HOST: "shipping-{{ env }}.naginenihariaws.store"
REDIS_HOST: "redis-{{ env }}.naginenihariaws.store"
FRONTEND_HOST: "frontend-{{ env }}.naginenihariaws.store"
PAYMENT_HOST: "payment-{{ env }}.naginenihariaws.store"